azure_short_region      = "uks"
azure_region            = "UK South"
azure_short_region_dr   = "ukw"
azure_region_dr         = "UK West"
enabled                 = "true"
dr_enabled              = "true"

appsp_tier  = "Standard"
appsp_size  = "S1"
appsp_kind  = "Windows"