export const DNB_REMOTESEARCH_GET = "DNB_REMOTESEARCH_GET";
export const DNB_REMOTESEARCH_GET_SUCCESS = "DNB_REMOTESEARCH_GET_SUCCESS";
export const DNB_REMOTESEARCH_GET_ERROR = "DNB_REMOTESEARCH_GET_ERROR";

export const DNB_REMOTESEARCH_GET_DETAILS = "DNB_REMOTESEARCH_GET_DETAILS";
export const DNB_GET_DETAILS = "DNB_GET_DETAILS";
export const DNB_GET_DETAILS_SUCCESS = "DNB_GET_DETAILS_SUCCESS";
export const DNB_GET_DETAILS_ERROR = "DNB_GET_DETAILS_ERROR";
export const DNB_GET_DETAILS_TASK_STARTED = "DNB_GET_DETAILS_TASK_STARTED";
export const DNB_GET_DNBPCI = "DNB_GET_DNBPCI";
export const DNB_GET_DNBPCI_SUCCESS = "DNB_GET_DNBPCI_SUCCESS";
export const DNB_GET_DNBPKYC = "DNB_GET_DNBPKYC";
export const DNB_GET_DNBPKYC_SUCCESS = "DNB_GET_DNBPKYC_SUCCESS";

export const DNB_GET_DNBPVI = "DNB_GET_DNBPVI";
export const DNB_GET_DNBPVI_SUCCESS = "DNB_GET_DNBPVI_SUCCESS";

export const DNB_GET_DNBPCL = "DNB_GET_DNBPCL";
export const DNB_GET_DNBPCL_SUCCESS = "DNB_GET_DNBPCL_SUCCESS";

export const DNB_GET_DNBPML = "DNB_GET_DNBPML";
export const DNB_GET_DNBPML_SUCCESS = "DNB_GET_DNBPML_SUCCESS";

export const DNB_GET_DNBPCR = "DNB_GET_DNBPCR";
export const DNB_GET_DNBPCR_SUCCESS = "DNB_GET_DNBPCR_SUCCESS";

export const DNB_GET_DNBPLEB = "DNB_GET_DNBPLEB";
export const DNB_GET_DNBPLEB_SUCCESS = "DNB_GET_DNBPLEB_SUCCESS";

export const DNB_GET_DNBPLEJ = "DNB_GET_DNBPLEJ";
export const DNB_GET_DNBPLEJ_SUCCESS = "DNB_GET_DNBPLEJ_SUCCESS";

export const DNB_GET_DNBPLES = "DNB_GET_DNBPLES";
export const DNB_GET_DNBPLES_SUCCESS = "DNB_GET_DNBPLES_SUCCESS";

export const DNB_GET_DNBPMED = "DNB_GET_DNBPMED";
export const DNB_GET_DNBPMED_SUCCESS = "DNB_GET_DNBPMED_SUCCESS";

export const DNB_GET_DNBPPR = "DNB_GET_DNBPPR";
export const DNB_GET_DNBPPR_SUCCESS = "DNB_GET_DNBPPR_SUCCESS";

export const DNB_GET_DNBPOWN = "DNB_GET_DNBPOWN";
export const DNB_GET_DNBPOWN_SUCCESS = "DNB_GET_DNBPOWN_SUCCESS";

export const DNB_GET_DNBPCOMP = "DNB_GET_DNBPCOMP";
export const DNB_GET_DNBPCOMP_SUCCESS = "DNB_GET_DNBPCOMP_SUCCESS";
export const DNB_GET_CLEAR_STATE = "DNB_GET_CLEAR_STATE";
