name: Example - AzureSQL

resources:
  repositories:
    - repository: Modules
      type: git
      name: PSCloudModules\TerraformModules

trigger: none

stages:
  - stage: build
    displayName: SQL Build
    jobs:
      - deployment: terraform_AzureSQL
        displayName: Terraform - AzureSQL
        pool: windows-latest
        variables:
        - group: terraform_azure_creds
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self 
              - checkout: Modules

              - powershell: terraform init
                displayName: TF Init
                workingDirectory: $(System.DefaultWorkingDirectory)\$(Build.Repository.Name)
                env:
                  ARM_CLIENT_ID: $(arm_client_id)
                  ARM_CLIENT_SECRET: $(arm_client_secret)
                  ARM_SUBSCRIPTION_ID: $(arm_subscription_id)
                  ARM_TENANT_ID: $(arm_tenant_id)

              - powershell: terraform plan -var-file="terraform.tfvars" -out=plan
                displayName: TF Plan
                workingDirectory: $(System.DefaultWorkingDirectory)\$(Build.Repository.Name)
                env:
                  ARM_CLIENT_ID: $(arm_client_id)
                  ARM_CLIENT_SECRET: $(arm_client_secret)
                  ARM_SUBSCRIPTION_ID: $(arm_subscription_id)
                  ARM_TENANT_ID: $(arm_tenant_id)

              - powershell: terraform apply plan
                displayName: TF Apply
                workingDirectory: $(System.DefaultWorkingDirectory)\$(Build.Repository.Name)
                env:
                  ARM_CLIENT_ID: $(arm_client_id)
                  ARM_CLIENT_SECRET: $(arm_client_secret)
                  ARM_SUBSCRIPTION_ID: $(arm_subscription_id)
                  ARM_TENANT_ID: $(arm_tenant_id)
