platform_state_key_name="platform.terraform.tfstate"
platform_state_container_name="terraform-container-ukw-prod"
platform_state_storage_account_name="terraformukwprod"
platform_state_resource_group_name = "terraform-rg-ukw-prod"

tenant_id = "8cee18df-5e2a-4664-8d07-0566ffea6dcd"
spn_app_id = "3d88a81a-1f2f-47a3-b5ac-acd03cd2142b"
spn_object_id = "0b497959-78fe-419f-83fe-8a8608a83443"
subscription_id = "97537777-853f-4194-9301-8eab79b3c259"

azure_short_region = "uks"
azure_region = "UK South"
project = "apps"
app = "shared"
app_shortname = "shared"
contact = "Ahmet Demir"
contact_details = "ext 10129"
contact_email = "ahmet.demir@britinsurance.com"
costcentre = "N37"
description = "API Management"

subcategory = "shared-services"

environment_type = "prod"

azure_short_region_dr = "ukw"
azure_region_dr = "UK West"

apis = [{ Name = "britcache-eclipse", ResourceGroup = "uwac-britcache-rg-uks-prd", PrimaryBaseUrl = "https://britcache-api-eclipse-func-prd.azurewebsites.net/api/v2/", SecondaryBaseUrl = "https://britcache-api-eclipse-func-ukw-prd.azurewebsites.net/api/v2/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/britcacheeclipse", FrontEnd = "api.britinsurance.com" , RewriteUrl="api/v2/",Cors="https://abz.com"},
        { Name = "britcache-mds", ResourceGroup = "uwac-britcache-rg-uks-prd", PrimaryBaseUrl = "https://britcache-api-mds-func-prd.azurewebsites.net/api/v2/", SecondaryBaseUrl = "https://britcache-api-mds-func-ukw-prd.azurewebsites.net/api/v2/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/britcachemds", FrontEnd = "api.britinsurance.com" , RewriteUrl="api/v2/",Cors="https://abz.com"},
        { Name = "britcache-broker", ResourceGroup = "uwac-britcache-rg-uks-prd", PrimaryBaseUrl = "https://britcache-api-broker-func-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://britcache-api-broker-func-ukw-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/britcachebroker", FrontEnd = "api.britinsurance.com" , RewriteUrl="api/v1/",Cors="https://abz.com"},
        { Name = "britcache-policy", ResourceGroup = "uwac-reference-creation-rg-uks-prd", PrimaryBaseUrl = "https://britcache-api-britpolicy-func-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://britcache-api-britpolicy-func-uks-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "openapi+json-link", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/britcachepolicy", FrontEnd = "api.britinsurance.com", RewriteUrl="api/v1/" ,Cors="https://abz.com"},
        { Name = "keas", ResourceGroup = "ki-services-rg-uks-prd", PrimaryBaseUrl = "https://ki-keas-api-func-uks-prd.azurewebsites.net/api/", SecondaryBaseUrl = "https://ki-keas-api-func-ukw-prd.azurewebsites.net/api/", APIDefinitionFormat = "openapi+json-link", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/keas", FrontEnd = "api.britinsurance.com", RewriteUrl="api/",Cors="https://abz.com" },
        { Name = "dnb", ResourceGroup = "uwac-reference-creation-rg-uks-prd", PrimaryBaseUrl = "https://dnb-api-func-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://dnb-api-func-uks-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/dnb", FrontEnd = "api.britinsurance.com", RewriteUrl="api/v1/",Cors="https://abz.com" },
        { Name = "dowjones", ResourceGroup = "uwac-reference-creation-rg-uks-prd", PrimaryBaseUrl = "https://dow-jones-api-func-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://dow-jones-api-func-uks-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/dowjones", FrontEnd = "api.britinsurance.com" , RewriteUrl="api/v1/",Cors="https://abz.com"},
        { Name = "ki-quote", ResourceGroup = "ki-services-rg-uks-prd", PrimaryBaseUrl = "https://ki-quote-api-webapp-uks-prd.azurewebsites.net/api/v2/", SecondaryBaseUrl = "https://ki-quote-api-webapp-ukw-prd.azurewebsites.net/api/v2/", APIDefinitionFormat = "openapi+json-link", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/kiquote", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v2/",Cors="https://opus" },
        { Name = "ki-pricing", ResourceGroup = "ki-services-rg-uks-prd", PrimaryBaseUrl = "https://ki-pricing-api-func-uks-prd.azurewebsites.net/api/v2/", SecondaryBaseUrl = "https://ki-pricing-api-func-ukw-prd.azurewebsites.net/api/v2/", APIDefinitionFormat = "openapi+json-link", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/pricing", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v2/" ,Cors="https://abz.com"},
        { Name = "ki-cat-modelling", ResourceGroup = "ki-services-rg-uks-prd", PrimaryBaseUrl = "https://ki-cat-modelling-api-func-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://ki-cat-modelling-api-func-ukw-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "openapi+json-link", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/catmodelling", FrontEnd = "api.ki-insurance.com" , RewriteUrl="api/v1/",Cors="https://abz.com"},
        { Name = "ext-britcache-eclipse", ResourceGroup = "uwac-ki-rg-uks-prd", PrimaryBaseUrl = "https://ki-interface-api-func-uks-prd.azurewebsites.net/api/v1/britcache/eclipse/", SecondaryBaseUrl = "https://ki-interface-api-func-ukw-prd.azurewebsites.net/api/v1/britcache/eclipse/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/britcacheeclipse", FrontEnd = "api.britinsurance.com", RewriteUrl="api/v2/",Cors="https://abz.com" },
        { Name = "ext-britcache-mds", ResourceGroup = "uwac-ki-rg-uks-prd", PrimaryBaseUrl = "https://ki-interface-api-func-uks-prd.azurewebsites.net/api/v1/britcache/mds/", SecondaryBaseUrl = "https://ki-interface-api-func-ukw-prd.azurewebsites.net/api/v1/britcache/mds/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/britcachemds", FrontEnd = "api.britinsurance.com", RewriteUrl="api/v2/" ,Cors="https://abz.com"},
        { Name = "ext-britcache-broker", ResourceGroup = "uwac-ki-rg-uks-prd", PrimaryBaseUrl = "https://ki-interface-api-func-uks-prd.azurewebsites.net/api/v1/britcache/broker/", SecondaryBaseUrl = "https://ki-interface-api-func-ukw-prd.azurewebsites.net/api/v1/britcache/broker/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/britcachebroker", FrontEnd = "api.britinsurance.com", RewriteUrl="api/v1/",Cors="https://abz.com" },
        { Name = "ext-dnb", ResourceGroup = "uwac-ki-rg-uks-prd", PrimaryBaseUrl = "https://ki-interface-api-func-uks-prd.azurewebsites.net/api/v1/dnb/", SecondaryBaseUrl = "https://ki-interface-api-func-uks-prd.azurewebsites.net/api/v1/dnb/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/dnb", FrontEnd = "api.britinsurance.com", RewriteUrl="api/v1/",Cors="https://abz.com"  },
	{ Name = "ext-ki-quote", ResourceGroup = "uwac-ki-rg-uks-prd", PrimaryBaseUrl = "https://ki-interface-api-func-uks-prd.azurewebsites.net/api/v1/quote/", SecondaryBaseUrl = "https://ki-interface-api-func-ukw-prd.azurewebsites.net/api/v1/quote/", APIDefinitionFormat = "openapi+json-link", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/kiquote", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v2/",Cors="https://abz.com"  },
        { Name = "ext-ki-pricing", ResourceGroup = "uwac-ki-rg-uks-prd", PrimaryBaseUrl = "https://ki-interface-api-func-uks-prd.azurewebsites.net/api/v1/pricing/", SecondaryBaseUrl = "https://ki-interface-api-func-ukw-prd.azurewebsites.net/api/v1/pricing/", APIDefinitionFormat = "openapi+json-link", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/pricing", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v2/",Cors="https://abz.com"  },
        { Name = "most-material", ResourceGroup = "containers-rg-uks-prd", PrimaryBaseUrl = "https://mostmaterial-api-webapp-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://mostmaterial-api-webapp-ukw-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/mostmaterial", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v1/",Cors="https://abz.com" }	,
        { Name = "adjustment", ResourceGroup = "containers-rg-uks-prd", PrimaryBaseUrl = "https://adjustment-layer-api-webapp-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://adjustment-layer-api-webapp-ukw-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/adjustmentlayer", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v1/",Cors="https://abz.com" },
         { Name = "nom-lead", ResourceGroup = "containers-rg-uks-prd", PrimaryBaseUrl = "https://ati-nom-lead-webapp-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://ati-nom-lead-webapp-ukw-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/atinomlead", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v1/", Cors="https://abz.com"},
        { Name = "data-access-metadata", ResourceGroup = "containers-rg-uks-prd", PrimaryBaseUrl = "https://data-access-metadata-webapp-uks-prd.azurewebsites.net/api/v1/", SecondaryBaseUrl = "https://data-access-metadata-webapp-ukw-prd.azurewebsites.net/api/v1/", APIDefinitionFormat = "swagger-link-json", SwaggerUrl = "https://swagger-api-func-uks-prd.azurewebsites.net/api/swagger/json/dataaccessmetadata", FrontEnd = "api.ki-insurance.com", RewriteUrl="api/v1/", Cors="https://abz.com"}
       ]