export const AAD_ACQUIRE_ACCESS_TOKEN = "AAD_ACQUIRE_ACCESS_TOKEN";
export const AAD_LOGIN_SUCCESS = "AAD_LOGIN_SUCCESS";
export const AAD_LOGOUT_SUCCESS = "AAD_LOGOUT_SUCCESS";
export const AAD_LOGIN = "AAD_LOGIN";
export const AAD_LOGIN_ERROR = "AAD_LOGIN_ERROR";
export const AAD_ACCESS_TOKEN_RECEIVED = "AAD_ACCESS_TOKEN_RECEIVED";
export const AAD_CALLBACK_PROCESSED = "AAD_CALLBACK_PROCESSED";
